const quizData = [
    {
        "question": "Which language runs in a web browser?",
        "a": "Java",
        "b": "C",
        "c": "Python",
        "d": "JavaScript",
        "correct": "d",
    },
    {
        "question": "What does CSS stand for?",
        "a": "Central Style Sheets",
        "b": "Cascading Style Sheets",
        "c": "Cascading Simple Sheets",
        "d": "Cars SUVs Sailboats",
        "correct": "b",
    },
    {
        "question": "What does HTML stand for?",
        "a": "Hypertext Markup Language",
        "b": "Hypertext Markdown Language",
        "c": "Hyperloop Machine Language",
        "d": "Helicopters Terminals Motorboats Lamborghinis",
        "correct": "a",
    },
    {
        "question": "What year was JavaScript launched?",
        "a": "1996",
        "b": "1995",
        "c": "1994",
        "d": "none of the above",
        "correct": "b",
    },
    {
        "question": "Who invented JavaScript?",
        "a": "Douglas Crockford",
        "b": "Sheryl Sandberg",
        "c": "Brendan Eich",
        "d": "Mark Zuckerberg",
        "correct": "c",
    },
    {
        "question": "Which of the following is a JavaScript framework?",
        "a": "React",
        "b": "Laravel",
        "c": "Django",
        "d": "Flask",
        "correct": "a",
    },
    {
        "question": "What does JSON stand for?",
        "a": "JavaScript Object Notation",
        "b": "JavaScript Online Notation",
        "c": "JavaScript Object Native",
        "d": "JavaScript Offline Notation",
        "correct": "a",
    },
    {
        "question": "Which company developed JavaScript?",
        "a": "Microsoft",
        "b": "Google",
        "c": "Netscape",
        "d": "Apple",
        "correct": "c",
    },
    {
        "question": "Which one is not a JavaScript data type?",
        "a": "Number",
        "b": "String",
        "c": "Boolean",
        "d": "Float",
        "correct": "d",
    },
    {
        "question": "How do you declare a JavaScript variable?",
        "a": "v myVar;",
        "b": "var myVar;",
        "c": "variable myVar;",
        "d": "myVar;",
        "correct": "b",
    },
    {
        "question": "Which company developed React?",
        "a": "Google",
        "b": "Facebook",
        "c": "Microsoft",
        "d": "Apple",
        "correct": "b",
    },
    {
        "question": "What is the purpose of 'use strict' in JavaScript?",
        "a": "Enable strict mode",
        "b": "Enable lenient mode",
        "c": "Change the scope of variables",
        "d": "None of the above",
        "correct": "a",
    },
    {
        "question": "Which method is used to parse a JSON string into a JavaScript object?",
        "a": "JSON.parse()",
        "b": "JSON.stringify()",
        "c": "JSON.objectify()",
        "d": "JSON.convert()",
        "correct": "a",
    },
    {
        "question": "Which HTML element is used to embed JavaScript code?",
        "a": "<script>",
        "b": "<javascript>",
        "c": "<js>",
        "d": "<code>",
        "correct": "a",
    },
    {
        "question": "Which keyword is used to define a constant in JavaScript?",
        "a": "let",
        "b": "var",
        "c": "const",
        "d": "constant",
        "correct": "c",
    },
    {
        "question": "How do you write a comment in JavaScript?",
        "a": "// This is a comment",
        "b": "# This is a comment",
        "c": "/* This is a comment */",
        "d": "<!-- This is a comment -->",
        "correct": "a",
    },
    {
        "question": "Which operator is used to assign a value to a variable?",
        "a": "*",
        "b": "=",
        "c": "+",
        "d": "-",
        "correct": "b",
    },
    {
        "question": "What is the correct way to write an 'if' statement in JavaScript?",
        "a": "if i = 5",
        "b": "if (i == 5)",
        "c": "if i == 5 then",
        "d": "if i equals 5",
        "correct": "b",
    },
    {
        "question": "How can you add a comment in a JavaScript file?",
        "a": "// This is a comment",
        "b": "<!-- This is a comment -->",
        "c": "# This is a comment",
        "d": "/* This is a comment */",
        "correct": "a",
    },
    {
        "question": "Which event occurs when the user clicks on an HTML element?",
        "a": "onmouseover",
        "b": "onchange",
        "c": "onclick",
        "d": "onmouseclick",
        "correct": "c",
    },
    {
        "question": "Which JavaScript method is used to access an HTML element by id?",
        "a": "getElementById()",
        "b": "getElementByClass()",
        "c": "getElement()",
        "d": "querySelector()",
        "correct": "a",
    },
    {
        "question": "How do you find the largest number of 5 and 10 in JavaScript?",
        "a": "Math.ceil(5,10)",
        "b": "Math.max(5,10)",
        "c": "ceil(5,10)",
        "d": "Math.floor(5,10)",
        "correct": "b",
    },
    {
        "question": "Which company owns JavaScript?",
        "a": "Oracle",
        "b": "Mozilla",
        "c": "Netscape",
        "d": "Oracle and Netscape",
        "correct": "c",
    },
    {
        "question": "Which one is a looping structure in JavaScript?",
        "a": "for",
        "b": "while",
        "c": "forEach",
        "d": "All of the above",
        "correct": "d",
    },
    {
        "question": "What is the output of '2' + 2 in JavaScript?",
        "a": "22",
        "b": "4",
        "c": "NaN",
        "d": "undefined",
        "correct": "a",
    },
    {
        "question": "How can you detect the user's browser in JavaScript?",
        "a": "navigator.appName",
        "b": "browser.name",
        "c": "navigator.browser",
        "d": "userAgent.browser",
        "correct": "a",
    },
    {
        "question": "Which method is used to join two or more arrays in JavaScript?",
        "a": "concat()",
        "b": "push()",
        "c": "merge()",
        "d": "join()",
        "correct": "a",
    },
    {
        "question": "Which symbol is used for comments in JavaScript?",
        "a": "//",
        "b": "#",
        "c": "/* */",
        "d": "--",
        "correct": "a",
    },
    {
        "question": "Which of the following is a ternary operator in JavaScript?",
        "a": "?",
        "b": "??",
        "c": "?:",
        "d": "+=",
        "correct": "a",
    },
    {
        "question": "Which is the correct way to define a function in JavaScript?",
        "a": "function myFunction()",
        "b": "func myFunction()",
        "c": "define myFunction()",
        "d": "method myFunction()",
        "correct": "a",
    },
    {
        "question": "Which built-in method removes the last element from an array in JavaScript?",
        "a": "pop()",
        "b": "shift()",
        "c": "slice()",
        "d": "splice()",
        "correct": "a",
    },
    {
        "question": "Which HTML element is used to link external JavaScript files?",
        "a": "<link>",
        "b": "<script>",
        "c": "<js>",
        "d": "<src>",
        "correct": "b",
    },
    {
        "question": "Which of the following is not a reserved keyword in JavaScript?",
        "a": "if",
        "b": "catch",
        "c": "finally",
        "d": "final",
        "correct": "d",
    },
    {
        "question": "What is the keyword used to create a class in JavaScript?",
        "a": "class",
        "b": "object",
        "c": "createClass",
        "d": "constructor",
        "correct": "a",
    },
    {
        "question": "Which array method is used to add elements to the end of an array in JavaScript?",
        "a": "push()",
        "b": "pop()",
        "c": "append()",
        "d": "unshift()",
        "correct": "a",
    },
    {
        "question": "What is the difference between == and === in JavaScript?",
        "a": "== compares value only, === compares value and type",
        "b": "== compares type only, === compares value",
        "c": "There is no difference",
        "d": "=== is used for comparison, == is not",
        "correct": "a",
    },
    {
        "question": "Which keyword is used to return a value from a function in JavaScript?",
        "a": "return",
        "b": "break",
        "c": "yield",
        "d": "output",
        "correct": "a",
    },
    {
        "question": "What does the method forEach() do in JavaScript?",
        "a": "Iterates through an array",
        "b": "Adds elements to an array",
        "c": "Searches for an element in an array",
        "d": "Reverses the order of an array",
        "correct": "a",
    },
    {
        "question": "Which of these is not a JavaScript framework?",
        "a": "React",
        "b": "Angular",
        "c": "Vue",
        "d": "Rails",
        "correct": "d",
    },
    {
        "question": "Which of the following is used to handle exceptions in JavaScript?",
        "a": "try...catch",
        "b": "try...finally",
        "c": "throw",
        "d": "error",
        "correct": "a",
    },
    {
        "question": "Which array method sorts the elements of an array in JavaScript?",
        "a": "sort()",
        "b": "filter()",
        "c": "map()",
        "d": "reduce()",
        "correct": "a",
    },
    {
        "question": "Which of the following methods can be used to log data to the console in JavaScript?",
        "a": "console.log()",
        "b": "console.error()",
        "c": "console.info()",
        "d": "All of the above",
        "correct": "d",
    },
    {
        "question": "Which method removes whitespace from both ends of a string in JavaScript?",
        "a": "trim()",
        "b": "slice()",
        "c": "replace()",
        "d": "split()",
        "correct": "a",
    },
    {
        "question": "Which built-in object is used to store keyed collections of values in JavaScript?",
        "a": "Array",
        "b": "Object",
        "c": "Map",
        "d": "Set",
        "correct": "c",
    }
];
